services:
  qbittorrent:
    image: trigus42/qbittorrentvpn
    container_name: qbittorrent
    environment:
      - VPN_TYPE=openvpn
      - VPN_USERNAME=${CYBERGHOST_USER}
      - VPN_PASSWORD=${CYBERGHOST_PASSWORD}
      - WEBUI_PASSWORD=${WEBUI_PASSWORD}
    volumes:
      - qbittorrent_config:/config
      - torrents_data:/downloads
    ports:
      - "8080:8080"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/net/tun

  samba:
    image: dperson/samba
    container_name: samba
    volumes:
      - torrents_data:/shared
      - ./smb.conf:/etc/samba/smb.conf:ro
    ports:
      - "139:139"
      - "445:445"
    restart: unless-stopped
    networks:
      - fileshare_net
    command: >
      -u "${SAMBA_USER};${SAMBA_PASSWORD}"

networks:
  fileshare_net:
    driver: bridge

volumes:
  qbittorrent_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APPDATA_PATH}/qBittorrent
  torrents_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TORRENTS_DATA_PATH}

